on:
  push:
    branchs:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cloudflare/wrangler-action@v3
        if: "! contains(github.event.commits[0].message, '[no ci]')"
        with:
          apiToken: ${{ secrets.CLOUDFLARE_TOKEN }}
          accountId: ${{ secrets.ACCOUNT_ID }}
          command: deploy
